const BemEstar = () => {
    return ( 
     [
    "Cuide do seu corpo, é o único lugar que você tem para viver.",
    "A saúde é o maior presente, o contentamento a maior riqueza.",
    "A mente é como um jardim; o que você planta é o que cresce.",
    "Faça da sua saúde uma prioridade.",
    "Respire fundo e saiba que tudo vai ficar bem.",
    "A paz interior começa no momento em que você decide não permitir que outra pessoa ou evento controle suas emoções.",
    "Você merece momentos de descanso e autocuidado.",
    "A gratidão é a chave para a felicidade.",
    "Seja gentil consigo mesmo, você está fazendo o melhor que pode.",
    "O equilíbrio é essencial para uma vida saudável.",
    "A felicidade é uma jornada, não um destino.",
    "O autocuidado não é egoísmo, é necessidade.",
    "Cuide da sua mente, ela é o seu bem mais precioso.",
    "A serenidade vem de dentro, procure cultivá-la diariamente.",
    "Um corpo saudável é uma mente saudável.",
    "Cada dia é uma nova oportunidade para cuidar de si mesmo.",
    "Faça da sua saúde mental uma prioridade.",
    "Ame-se o suficiente para viver um estilo de vida saudável.",
    "Cuide de você por inteiro: corpo, mente e espírito.",
    "A meditação é o alimento para a alma.",
    "O descanso é tão importante quanto o trabalho duro.",
    "Seja a mudança que você deseja ver em sua saúde.",
    "A tranquilidade vem quando você aprende a deixar ir.",
    "Encontre tempo para fazer as coisas que você ama.",
    "Cuide do seu bem-estar, ele afeta tudo o que você faz.",
    "Pequenos hábitos saudáveis levam a grandes transformações.",
    "Você merece paz, alegria e bem-estar.",
    "Mantenha o equilíbrio entre o trabalho e o descanso.",
    "Priorize o que traz paz para a sua alma.",
    "A saúde mental é tão importante quanto a saúde física.",
    "Um corpo descansado é um corpo saudável.",
    "Cuide da sua energia, ela é limitada.",
    "Faça do bem-estar uma parte essencial do seu dia.",
    "Ame a si mesmo incondicionalmente.",
    "A calma é o poder da mente sob controle.",
    "O bem-estar começa com uma mente tranquila.",
    "Você merece tempo para relaxar e recarregar.",
    "O seu bem-estar emocional é importante.",
    "Cuidar de si mesmo é um ato de amor-próprio.",
    "A verdadeira felicidade vem de cuidar do seu bem-estar.",
    "Você é digno de uma vida cheia de paz e saúde.",
    "Cultive o hábito de cuidar de si mesmo todos os dias.",
    "A paz interior reflete em sua saúde física.",
    "Escolha o bem-estar a cada dia.",
    "Seu corpo e mente merecem o melhor cuidado.",
    "Um coração tranquilo traz paz ao corpo.",
    "Invista no seu bem-estar, vale a pena.",
    "Sua saúde é seu maior patrimônio.",
    "Encontre a calma em meio ao caos.",
    "O bem-estar é a base para uma vida plena.",
    "Sua mente e corpo agradecem cada ato de cuidado.",
    "A paz começa com um pensamento.",
    "Dê a si mesmo o presente do bem-estar.",
    "Cuidar da mente é tão importante quanto cuidar do corpo.",
    "A gratidão transforma o que temos em suficiente.",
    "Cada respiração é uma nova chance de paz.",
    "O autocuidado é a base para uma vida saudável.",
    "Você é responsável pelo seu próprio bem-estar.",
    "O bem-estar vem de dentro.",
    "Escolha a calma em vez do estresse.",
    "Sua saúde merece a sua atenção total.",
    "O cuidado com a mente e corpo é uma forma de amor-próprio.",
    "A saúde é um estado de completo bem-estar físico, mental e social.",
    "A paz interior começa quando você decide não permitir que outros controlem suas emoções.",
    "A prática do autocuidado deve ser diária.",
    "O equilíbrio entre corpo e mente é a chave para o bem-estar.",
    "A serenidade é o novo luxo.",
    "Cuide de si mesmo como você cuidaria de alguém que ama.",
    "A paz é o resultado do reentendimento de sua própria mente.",
    "Seu bem-estar deve ser uma prioridade.",
    "Pequenos cuidados diários trazem grandes benefícios à saúde.",
    "A verdadeira saúde começa com o autocuidado.",
    "Faça do seu bem-estar uma prioridade.",
    "A paz interior é o maior dos tesouros.",
    "Seja gentil com seu corpo, ele é seu lar.",
    "A tranquilidade é o novo sucesso.",
    "A saúde mental é a base para uma vida plena.",
    "A verdadeira riqueza é a saúde.",
    "A mente tranquila é a chave para o bem-estar.",
    "Seja o guardião da sua paz interior.",
    "A saúde é um reflexo do cuidado consigo mesmo.",
    "A paz interior vem de uma mente em harmonia.",
    "O bem-estar é um estado de espírito.",
    "Cuide de sua mente como você cuida de seu corpo.",
    "O autocuidado é um ato de coragem.",
    "O descanso é tão importante quanto a atividade.",
    "Sua paz interior vale todo o esforço.",
    "O bem-estar é a soma de hábitos saudáveis.",
    "A serenidade é o prêmio da mente tranquila.",
    "Cuide da sua saúde mental, ela é o pilar da sua vida.",
    "A paz de espírito é o maior dos bens.",
    "A saúde é o equilíbrio entre corpo, mente e espírito.",
    "Você merece uma vida plena de bem-estar.",
    "Cuide de si mesmo, você é valioso.",
    "A saúde começa com uma mente tranquila.",
    "O autocuidado é o maior investimento que você pode fazer.",
    "A paz é o novo poder.",
    "Cuide de sua saúde mental todos os dias.",
    "Seu corpo merece descanso e cuidado.",
    "O bem-estar é um estilo de vida.",
    "A paz interior é o verdadeiro sucesso.",
    "A calma é a chave para o bem-estar.",
    "Sua saúde é seu bem mais precioso.",
    "Cuide da sua mente, ela define sua realidade.",
    "A felicidade é o reflexo do bem-estar interior.",
    "Você merece uma vida cheia de saúde e paz.",
    "O autocuidado é o primeiro passo para o bem-estar.",
    "A serenidade é o resultado do equilíbrio interior.",
    "O descanso é essencial para a saúde.",
    "Sua paz de espírito é sagrada.",
    "A saúde é o maior dos presentes.",
    "O bem-estar é um reflexo do autocuidado.",
    "A mente tranquila traz clareza e paz.",
    "Cuide de si mesmo com amor e carinho.",
    "O equilíbrio é a base da saúde.",
    "A paz interior é o verdadeiro bem-estar.",
    "Seja gentil com você mesmo, você merece.",
    "A saúde começa com o cuidado consigo mesmo.",
    "O bem-estar é a soma de escolhas diárias.",
    "A tranquilidade é o reflexo de uma mente em paz.",
    "Cuide da sua mente, ela é seu bem mais valioso.",
    "O autocuidado é um ato de respeito por si mesmo.",
    "A paz é o maior dos presentes.",
    "Sua saúde merece atenção e cuidado.",
    "A serenidade é o resultado de uma mente calma.",
    "O bem-estar é a chave para uma vida plena.",
    "Cuide de você, porque você é importante.",
    "A paz de espírito é o maior presente que você pode se dar.",
    "A saúde mental é a base de uma vida saudável.",
    "O autocuidado é o caminho para o bem-estar.",
    "A tranquilidade é o prêmio de uma mente em paz.",
    "Sua saúde é o reflexo do seu estilo de vida.",
    "Cuide de si mesmo como você cuidaria de quem você ama.",
    "O equilíbrio entre corpo e mente é a chave para o bem-estar.",
    "A paz interior é o segredo para uma vida plena.",
    "O autocuidado é o primeiro passo para uma vida saudável.",
    "A saúde começa na mente.",
    "A serenidade é a maior das riquezas.",
    "Cuide de si mesmo com carinho e respeito.",
    "A paz interior é o verdadeiro sucesso.",
    "Sua saúde mental merece toda a atenção.",
    "O bem-estar é o resultado de escolhas saudáveis.",
    "Cuide do seu corpo, é onde você vive.",
    "A tranquilidade é o novo luxo.",
    "O autocuidado é uma forma de amor-próprio.",
    "A paz é o maior dos tesouros.",
    "A saúde é o reflexo do cuidado consigo mesmo.",
    "A serenidade é o prêmio de uma mente tranquila.",
    "O bem-estar é um estado de espírito.",
    "Cuide de si mesmo todos os dias.",
    "A paz interior começa com o autocuidado.",
    "Sua saúde é o seu maior patrimônio.",
    "O equilíbrio é a chave para uma vida saudável.",
    "A tranquilidade é a base do bem-estar.",
    "Cuide da sua mente, ela é a chave para a sua saúde.",
    "O bem-estar é o reflexo do amor-próprio.",
    "A paz interior é o caminho para a felicidade.",
    "Cuide de si mesmo, você merece.",
    "A serenidade é o resultado de uma mente equilibrada.",
    "O autocuidado é o primeiro passo para o bem-estar"
    ]

     );
}
 
export default BemEstar;