 function Frases(){
    return(
        
        [
    "Nunca é tarde para aprender algo novo.",
    "Cada linha de código é um passo em direção ao sucesso.",
    "Erros são oportunidades de aprendizado disfarçadas.",
    "Não desista, cada bug resolvido é uma vitória.",
    "A prática leva à perfeição.",
    "Você é capaz de resolver qualquer problema.",
    "O segredo do sucesso é a persistência.",
    "Seu potencial é ilimitado.",
    "A jornada é tão importante quanto o destino.",
    "O código perfeito não existe, mas o progresso sim.",
    "A cada dia, você se torna um desenvolvedor melhor.",
    "Grandes coisas são alcançadas com pequenos passos.",
    "A falha é o primeiro passo para o sucesso.",
    "Confie em si mesmo e no seu processo.",
    "Programar é uma maratona, não uma corrida de velocidade.",
    "A única maneira de fazer um ótimo trabalho é amar o que você faz.",
    "Aprender a programar é como aprender uma nova linguagem.",
    "Seu esforço será recompensado.",
    "Não compare seu capítulo 1 com o capítulo 20 de alguém.",
    "Você pode mais do que imagina.",
    "Seja paciente, grandes coisas levam tempo.",
    "Cada desafio é uma oportunidade de crescimento.",
    "Acredite no processo, mesmo que seja difícil.",
    "Seu trabalho tem valor, mesmo que não veja agora.",
    "A única limitação é aquela que você impõe a si mesmo.",
    "A persistência é o caminho para o sucesso.",
    "Grandes coisas nunca vêm da zona de conforto.",
    "Programar é resolver problemas, e você é um solucionador de problemas.",
    "Todo desenvolvedor já foi um iniciante.",
    "O progresso é melhor que a perfeição.",
    "Você tem o poder de criar o que quiser.",
    "Desafie-se todos os dias.",
    "Seja resiliente, o sucesso vem com a persistência.",
    "A cada erro, você está mais próximo da solução.",
    "Nada é impossível para quem se dedica.",
    "Seu esforço hoje será a sua conquista amanhã.",
    "Seja curioso, a curiosidade é o combustível do aprendizado.",
    "Não há problema sem solução, apenas soluções a serem descobertas.",
    "O aprendizado é uma jornada, não um destino.",
    "Você é capaz de alcançar grandes coisas.",
    "Programar é transformar ideias em realidade.",
    "Você tem o controle sobre sua própria evolução.",
    "Pequenos avanços diários levam a grandes conquistas.",
    "Erros são oportunidades de aprender.",
    "A prática constante leva à excelência.",
    "O importante é continuar tentando.",
    "Desafios fazem parte do crescimento.",
    "Seu sucesso é o reflexo do seu esforço.",
    "Acredite no seu potencial.",
    "Programar é uma arte e você é o artista.",
    "Cada linha de código escrita é um passo adiante.",
    "A persistência é o que separa os vencedores dos desistentes.",
    "Você tem o poder de mudar o mundo com suas habilidades.",
    "Não tenha medo de falhar, tenha medo de não tentar.",
    "O futuro pertence àqueles que acreditam em seus sonhos.",
    "Sua jornada como desenvolvedor é única e valiosa.",
    "A prática é o caminho para a maestria.",
    "Cada problema tem uma solução, basta encontrá-la.",
    "Não se compare, apenas evolua.",
    "Seja paciente com o processo e gentil consigo mesmo.",
    "Você está no caminho certo, continue avançando.",
    "O sucesso é a soma de pequenos esforços repetidos diariamente.",
    "Não existe desafio que você não possa superar.",
    "Você é mais forte do que imagina.",
    "O aprendizado é infinito, e isso é algo incrível.",
    "A sua dedicação hoje será a sua recompensa amanhã.",
    "Seja corajoso, o mundo precisa das suas ideias.",
    "Cada novo dia é uma nova oportunidade para aprender.",
    "A perseverança sempre traz resultados.",
    "O importante é continuar, mesmo quando é difícil.",
    "Você tem o potencial para alcançar seus sonhos.",
    "Não tenha medo de errar, tenha medo de desistir.",
    "Todo especialista já foi um iniciante.",
    "Acreditar em si mesmo é o primeiro passo para o sucesso.",
    "Programar é uma jornada de aprendizado constante.",
    "Você está no controle do seu destino.",
    "Seja constante, a consistência traz resultados.",
    "O mundo precisa das suas habilidades e criatividade.",
    "Você é capaz de superar qualquer obstáculo.",
    "Nunca subestime o poder do esforço contínuo.",
    "O sucesso é a soma de pequenas vitórias diárias.",
    "Você tem a capacidade de criar algo incrível.",
    "Seja persistente, cada desafio superado é uma vitória.",
    "A prática regular é a chave para o domínio.",
    "Você é capaz de alcançar qualquer meta que estabelecer.",
    "Não desanime, o sucesso é uma questão de tempo.",
    "Você é mais capaz do que acredita.",
    "Acredite em si mesmo e no seu potencial.",
    "Cada pequeno passo conta para o progresso.",
    "O importante é continuar aprendendo e evoluindo.",
    "Você tem o poder de mudar sua realidade.",
    "O sucesso começa com a decisão de tentar.",
    "Você é mais forte do que pensa.",
    "A prática constante leva ao sucesso.",
    "Nunca subestime o poder de um pequeno passo.",
    "Você está no caminho certo, continue andando.",
    "Não há limites para o que você pode alcançar.",
    "Cada desafio é uma oportunidade de crescimento.",
    "Você é capaz de realizar grandes feitos.",
    "Não desista, você está mais perto do que imagina.",
    "Acredite, o esforço de hoje será a vitória de amanhã.",
    "Você é capaz de transformar suas ideias em realidade.",
    "Cada erro é um passo em direção ao sucesso.",
    "Nunca é tarde para recomeçar.",
    "Você tem o potencial para fazer a diferença.",
    "O sucesso vem para aqueles que não desistem.",
    "Você está evoluindo a cada dia.",
    "Nunca pare de aprender, o conhecimento é infinito.",
    "Acredite no processo, ele te levará longe.",
    "Você é mais capaz do que pensa.",
    "Cada desafio superado é uma vitória.",
    "A prática faz a perfeição.",
    "Você está no caminho certo, continue avançando.",
    "Não existe sucesso sem esforço.",
    "Você é mais forte do que qualquer obstáculo.",
    "Nunca subestime o poder da persistência.",
    "Você tem o poder de criar o futuro que deseja.",
    "Acredite, você é capaz de grandes coisas.",
    "Cada dia é uma nova oportunidade para crescer.",
    "Seja corajoso, os desafios são apenas degraus para o sucesso.",
    "Você está construindo seu próprio caminho.",
    "O sucesso é uma jornada, não um destino.",
    "Você tem o poder de mudar sua história.",
    "Cada linha de código escrita é um passo para o sucesso.",
    "Você é mais resiliente do que imagina.",
    "Acredite em si mesmo e siga em frente.",
    "Não tenha medo de errar, tenha medo de não tentar.",
    "Você está mais perto do sucesso do que imagina.",
    "O aprendizado é a chave para o crescimento.",
    "Você tem o poder de superar qualquer desafio.",
    "A persistência é a chave para o sucesso.",
    "Você é capaz de alcançar grandes coisas.",
    "Cada esforço vale a pena.",
    "O importante é continuar tentando, não desistir.",
    "Você está no caminho certo, continue andando.",
    "O sucesso vem para aqueles que são pacientes.",
    "Você tem o poder de transformar suas ideias em realidade.",
    "Acredite, você está no caminho certo.",
    "Você é mais forte do que qualquer obstáculo.",
    "Cada pequeno progresso é um passo em direção ao sucesso.",
    "Você está evoluindo a cada dia.",
    "Nunca pare de aprender, o conhecimento é poder.",
    "Acredite em si mesmo e no seu potencial.",
    "Você é capaz de realizar grandes coisas.",
    "Cada desafio superado é uma vitória.",
    "A prática faz a perfeição.",
    "Você está no controle do seu próprio destino.",
    "Não existe sucesso sem esforço.",
    "Você tem o poder de criar o futuro que deseja.",
    "Acredite, você é capaz de grandes coisas.",
    "Cada dia é uma nova oportunidade para crescer.",
    "Você está construindo seu próprio caminho.",
    "O sucesso é uma jornada, não um destino.",
    "Você é mais resiliente do que imagina.",
    "Acredite em si mesmo e siga em frente.",
    "Você está mais perto do sucesso do que imagina.",
    "Você tem o poder de superar qualquer desafio.",
    "Você é capaz de alcançar grandes coisas.",
    "Cada esforço vale a pena.",
    "O importante é continuar tentando.",
    "Você está no caminho certo, continue avançando.",
    "O sucesso vem para aqueles que são pacientes.",
    "Acredite, você está no caminho certo.",
    "Você é mais forte do que qualquer obstáculo.",
    "Você está evoluindo a cada dia.",
    "Acredite em si mesmo e no seu potencial.",
    "Cada pequeno progresso é um passo para o sucesso.",
    "Você está no controle do seu próprio destino.",
    "Você tem o poder de criar o futuro que deseja.",
    "Você é capaz de grandes coisas.",
    "Você está construindo seu próprio caminho.",
    "Você é mais resiliente do que imagina.",
    "Você está mais perto do sucesso do que imagina.",
    "Você tem o poder de superar qualquer desafio.",
    "O importante é continuar tentando.",
    "Você está no caminho certo, continue andando."
]

    );
}

export default Frases;